# Generated by Django 5.0.2 on 2024-03-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataCollector', '0002_device_datacollector_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='sn',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
