# Generated by Django 5.0.2 on 2024-06-28 13:06

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataCollector', '0004_datacollector_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacollector',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
