# Generated by Django 5.0.2 on 2024-07-31 11:51

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataCollector", "0005_alter_datacollector_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="HourlyAverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", django_jalali.db.models.jDateTimeField()),
                ("Lat_avg", models.FloatField()),
                ("Lng_avg", models.FloatField()),
                ("Humidity_avg", models.FloatField()),
                ("Temperature_avg", models.FloatField()),
                ("CO_avg", models.FloatField()),
                ("H2_avg", models.FloatField()),
                ("LPG_avg", models.FloatField()),
                ("CH4_avg", models.FloatField()),
                ("NOx_avg", models.FloatField()),
                ("CL2_avg", models.FloatField()),
                ("Alchohol_avg", models.FloatField()),
                ("CO2_avg", models.FloatField()),
                ("Toluen_avg", models.FloatField()),
                ("NH4_avg", models.FloatField()),
                ("Aceton_avg", models.FloatField()),
                ("PM1_0_avg", models.FloatField()),
                ("PM2_5_avg", models.FloatField()),
                ("PM10_avg", models.FloatField()),
                (
                    "device",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dataCollector.device",
                    ),
                ),
            ],
        ),
    ]
