# Generated by Django 5.0.2 on 2024-08-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataCollector", "0007_alter_hourlyaverage_hour"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="Aceton_avg",
            new_name="Aceton",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="Alchohol_avg",
            new_name="Alchohol",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="CH4_avg",
            new_name="CH4",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="CL2_avg",
            new_name="CL2",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="CO_avg",
            new_name="CO",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="CO2_avg",
            new_name="CO2",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="H2_avg",
            new_name="H2",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="Humidity_avg",
            new_name="Humidity",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="LPG_avg",
            new_name="LPG",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="Lat_avg",
            new_name="Lat",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="Lng_avg",
            new_name="Lng",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="NH4_avg",
            new_name="NH4",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="NOx_avg",
            new_name="NOx",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="PM10_avg",
            new_name="PM10",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="PM1_0_avg",
            new_name="PM1_0",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="PM2_5_avg",
            new_name="PM2_5",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="Temperature_avg",
            new_name="Temperature",
        ),
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="Toluen_avg",
            new_name="Toluen",
        ),
    ]
