# Generated by Django 5.0.2 on 2024-08-03 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataCollector", "0008_rename_aceton_avg_hourlyaverage_aceton_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hourlyaverage",
            old_name="hour",
            new_name="created_at",
        ),
    ]
