# Generated by Django 5.0.2 on 2024-08-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataCollector", "0009_rename_hour_hourlyaverage_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="hourlyaverage",
            name="aqi",
            field=models.FloatField(null=True),
        ),
    ]
